---
- hosts: all
  tasks:
  - name: Update homebrew
    homebrew: update_homebrew=yes upgrade_all=yes
  - name: Install homebrew packages
    homebrew: name={{ item }} state=present
    with_items:
      - awscli
      - bash-completion
      - docker
      - docker-machine
      - gibo
      - gimme
      - haskell-stack
      - htop-osx
      - hub
      - packer
      - pidof
      - pwgen
      - pyenv
      - rbenv
      - ruby-build
      - shellcheck
      - the_silver_searcher
      - tmux
      - tree
      - wget
  - name: Install aspell + en dictionary
    homebrew: name=aspell install_options=--with-lang-en state=present
  - name: Install cask packages
    homebrew_cask: name={{ item }} state=present
    with_items:
      - firefox
      - google-chrome
      - iterm2
      - lastpass
      - quicksilver
      - spectacle
      - spotify
      - vagrant
      - virtualbox
