---
- hosts: all
  tasks:
  - name: Update homebrew
    homebrew: update_homebrew=yes upgrade_all=yes
  - name: Install homebrew packages
    homebrew: name={{ item }} state=present
    with_items:
      - awscli
      - bash-completion
      - bluetoothconnector
      - gibo
      - github/gh/gh
      - haskell-stack
      - htop
      - hub
      - inetutils
      - jq
      - neovim
      - packer
      - pidof
      - pwgen
      - pyenv
      - pyenv-virtualenv
      - rbenv
      - reattach-to-user-namespace
      - ripgrep
      - ruby-build
      - shellcheck
      - tmux
      - tree
      - watch
      - wget
  - name: Install aspell + en dictionary
    homebrew: name=aspell install_options=--with-lang-en state=present
  - name: Install cask packages
    homebrew_cask: name={{ item }} state=present
    with_items:
      - docker
      - firefox
      - google-chrome
      - iterm2
      - lastpass
      - monitorcontrol
      - quicksilver
      - rectangle
      - spotify
      - vagrant
      - virtualbox
